language: c++

matrix:
  include:
    # Clang on OSX
    - env: MATRIX_EVAL="" CONF=""
      os: osx
      osx_image: xcode11
      compiler: clang

    # GCC and clang builds on Linux
    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--disable-output-edi"
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: &linuxaddons
        apt:
          sources: &sources
            - sourceline: 'ppa:ubuntu-toolchain-r-test'
          packages: &packages
            - libzmq3-dev
            - libzmq5
            - automake
            - libtool
            - libboost1.65-all-dev
            - libcurl4-openssl-dev
            - g++-9

    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF="--enable-output-raw"
      arch: amd64
      compiler: gcc
      addons: *linuxaddons

    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF=""
      arch: amd64
      compiler: gcc
      addons: *linuxaddons

    - env: MATRIX_EVAL="CC=gcc-9 CXX=g++-9" CONF=""
      arch: arm64
      compiler: gcc
      addons: *linuxaddons

    - env: MATRIX_EVAL="" CONF="--enable-output-raw"
      arch: amd64
      compiler: clang
      addons: &linuxclang40
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
          packages:
            - libzmq3-dev
            - libzmq5
            - automake
            - libtool
            - libboost1.65-all-dev
            - libcurl4-openssl-dev
            - clang-9

before_install:
  - eval "${MATRIX_EVAL}"
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
    brew install automake || true
    brew install zeromq || true
    brew install boost || true
    brew install curl || true
    fi

script:
  - |
    ./bootstrap.sh
    ./configure $CONF
    make

