language: c++
#sudo: required
dist: trusty

addons: &addons
  apt:
    sources: &sources
      - ubuntu-toolchain-r-test
    packages: &packages
      - libzmq3-dev
      - libzmq3
      - automake
      - libtool
      - libboost1.55-all-dev
      - libcurl4-openssl-dev
      - gcc-5
      - g++-5

compiler:
  - gcc

script:
  - |
    ./bootstrap.sh
    CC=gcc-5 CXX=g++-5 ./configure --disable-output-edi
    make
  - |
    ./bootstrap.sh
    CC=gcc-5 CXX=g++-5 ./configure
    make
  - |
    ./bootstrap.sh
    CC=gcc-5 CXX=g++-5 ./configure --enable-input-prbs --enable-input-test --enable-input-udp --enable-output-raw
    make

